### ISSUE TITLE
Latest build won't run Can't find Cookie Monster

### ISSUE THREAD

**Issue by ZapUser77** [ShahanaFarooqui/RTL#112]
**Describe the bug**
I updated to the latest using the following commands:
$ git reset --hard HEAD
$ git clean -f -d
$ git pull
$ npm install
Then ran, and received the following error:
internal/modules/cjs/loader.js:613
    throw err;
    ^

Error: Cannot find module 'cookie-parser'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:611:15)
    at Function.Module._load (internal/modules/cjs/loader.js:537:25)
    at Module.require (internal/modules/cjs/loader.js:665:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/pi/source/RTL/app.js:4:22)
    at Module._compile (internal/modules/cjs/loader.js:736:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
    at Function.Module._load (internal/modules/cjs/loader.js:560:3)

**Your environment**
* version of `lnd`: 0.6.0 
* operating system (`uname -a` on *Nix) Rasbian
* version of `btcd`, `bitcoind`, or other backend: BitcoinD

**Comment by ZapUser77** [comment]
LOL... Found the Cookie Monster...
(Helps if I actually run the commands I said I ran... forgot to run npm install)
