### ISSUE TITLE
Error running rtl after reboot - was starting fine right after install before I rebooted (ubuntu 16 - ARM7)

### ISSUE THREAD

**Issue by briansteven** [ShahanaFarooqui/RTL#124]
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '/home/admin/rtl'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

**Comment by briansteven** [comment]
LOL nevermind, I was just not in the right directory!
