### ISSUE TITLE
TypeError: tar.Extract is not a function

### ISSUE THREAD

**Issue by MrManPew** [ShahanaFarooqui/RTL#127]
**Describe the bug**
```
gyp info using node@10.15.3 | linux | arm
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.13
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 10.15.3
gyp verb command install [ '10.15.3' ]
gyp verb install input version string "10.15.3"
gyp verb install installing version: 10.15.3
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 0
gyp verb needs "installVersion" 9
gyp verb install version is no good; reinstalling
gyp verb ensuring nodedir is created /home/admin/.node-gyp/10.15.3
gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack TypeError: tar.Extract is not a function
gyp ERR! stack     at /home/admin/download/RTL/node_modules/node-gyp/lib/install.js:152:27
gyp ERR! stack     at /home/admin/download/RTL/node_modules/mkdirp/index.js:48:26
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:5)
gyp ERR! System Linux 4.14.71-v7+
gyp ERR! command "/usr/local/bin/node" "/home/admin/download/RTL/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/admin/download/RTL/node_modules/node-sass
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
Build failed with error code: 7
npm WARN @angular/compiler-cli@7.2.9 requires a peer of @angular/compiler@7.2.9 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.4.0 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN angular-user-idle@2.0.0 requires a peer of @angular/common@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-user-idle@2.0.0 requires a peer of @angular/core@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@4.3.0 requires a peer of @angular/compiler@>=2.3.1 <7.0.0 || >6.0.0-beta <7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@4.3.0 requires a peer of @angular/core@>=2.3.1 <7.0.0 || >6.0.0-beta <7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/@angular/compiler-cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.11.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.11.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/admin/.npm/_logs/2019-04-26T07_10_37_623Z-debug.log
```
**To Reproduce**
git clone
cd RTL 
npm install

**Your environment**
Linux raspberrypi 4.14.71-v7+ #1145 SMP Fri Sep 21 15:38:35 BST 2018 armv7l GNU/Linux
lnd version 0.6.0-beta commit=v0.6-beta
Bitcoin Core Daemon version v0.17.1
nmp 6.4.1
node v10.15.3

**Comment by codeShark149** [comment]
I am having the same exact problem in Raspberry 3B, armv7. Tried updating the node-gyp version. Still giving the same error.

**Comment by codeShark149** [comment]
Please find below the full log file, if that is of any help?

**Comment by ShahanaFarooqui** [comment]
@MrManPew , @codeShark149 Thanks for raising the issue. But, it is not directly related to RTL. As described in your error log: 'TypeError: tar.Extract is not a function', node-gyp's install.js file earlier had this erroneous code but it has already been removed and pushed to master branch 6 days back. 

We just successfully installed all RTL dependencies on Raspberrypi. Can you please verify your npm cache and install it again. It seems like your npm has an older library reference for node-gyp.

**Comment by ShahanaFarooqui** [comment]
@MrManPew, @codeShark149 Hi, Did you get a chance to install the dependencies again?

**Comment by saubyk** [comment]
Assuming the issue has been addressed. Close this ticket now.
Feel free to open another in case you face any problems.
Thanks.

**Comment by himsgupta1122** [comment]
I am still facing this error. ```ERROR TypeError: _tar.Extract is not a constructor``` Any resolution?

**Comment by ShahanaFarooqui** [comment]
Can you please confirm your NodeJS version? RTL is incompatible with v<16
