### ISSUE TITLE
Exception with custom authentication

### ISSUE THREAD

**Issue by sipsorcery** [ShahanaFarooqui/RTL#150]
**Describe the bug**
When starting with `node rtl` the error below occurs.

Seems similar to #87.

```
admin@btc:~/src/RTL$ node rtl
/home/admin/src/RTL/connect.js:219
                throw new Error(errMsg);
                ^

Error:
rtlPass hash conversion failed!
Custom Node Authentication can be set with RTL password only. Please set RTL Password through environment or RTL.conf
    at Object.connect.validateSingleNodeConfig (/home/admin/src/RTL/connect.js:219:9)
    at Object.connect.setSingleNodeConfiguration (/home/admin/src/RTL/connect.js:386:13)
    at Object.connect.setServerConfiguration (/home/admin/src/RTL/connect.js:423:13)
    at Object.<anonymous> (/home/admin/src/RTL/rtl.js:5:36)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

**Your environment**
* version of `lnd`
```
admin@btc:~/src/RTL$ lncli --lnddir /var/lib/lnd getinfo
{
        "version": "0.6.1-beta commit=v0.6.1-beta-12-gf8c824fb1d6c5ef8524148f59ea5650af65af98b",
```

* operating system (`uname -a` on *Nix)
```
admin@btc:~/src/RTL$ uname -a
Linux btc 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

admin@btc:~/src/RTL$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
```
* version of `btcd`, `bitcoind`, or other backend
```
admin@btc:~/src/RTL$ bitcoind --version
Bitcoin Core Daemon version v0.18.0
```

* any other relevant environment details
```
admin@btc:~/src/RTL$ git pull
Already up to date.
admin@btc:~/src/RTL$ git log
commit f49a246378e381d71ffd1ed7a3d27dfe95fcfaee (HEAD -> master, tag: v0.3.3, origin/master, origin/HEAD)
Author: ShahanaFarooqui <shahana.farooqui@gmail.com>
Date:   Tue May 14 21:59:46 2019 -0400
```

**Additional context**
```
admin@btc:~/src/RTL$ export | grep RTL
declare -x RTL_CONFIG_PATH="/var/lib/rtl/RTL.conf"
admin@btc:~/src/RTL$ cat /var/lib/rtl/RTL.conf
[Authentication]
macaroonPath=/var/lib/lnd/data/chain/bitcoin/mainnet
lndConfigPath=/etc/lnd/lnd.conf
nodeAuthType=CUSTOM
rtlPass=password

[SSO]
rtlSSO=0
rtlCookiePath=/var/lib/rtl
logoutRedirectLink=/login

[Settings]
flgSidenavOpened=true
flgSidenavPinned=true
menu=Vertical
menuType=Regular
theme=dark-blue
satsToBTC=false
bitcoindConfigPath=/etc/bitcoin/bitcoin.conf
enableLogging=true
port=3000
lndServerUrl=https://localhost:8080/v1
```

**Comment by ShahanaFarooqui** [comment]
@sipsorcery, thanks for opening the issue but it is not similar to #87. After reading password from your config, RTL is trying to delete this rtlPass from your RTL.conf and to add rtlPassHahed. Can you please ensure that the conf file is not read only and you are logged in as admin.

**Comment by sipsorcery** [comment]
Making admin the owner of the RTL.conf file fixed it, thanks.
