### ISSUE TITLE
 Cannot read property 'nodeAuthType' of undefined

### ISSUE THREAD

**Issue by NicolasDorier** [ShahanaFarooqui/RTL#182]
For some reason, my RTL don't want to start. To be clear, I can't really repro easily it happened only one time.

```
TypeError: Cannot read property 'nodeAuthType' of undefined
    at Object.connect.validateSingleNodeConfig (/RTL/connect.js:148:30)
    at Object.connect.setSingleNodeConfiguration (/RTL/connect.js:470:13)
    at Object.connect.setServerConfiguration (/RTL/connect.js:522:13)
    at Object.<anonymous> (/RTL/rtl.js:5:36)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
/RTL/connect.js:148
    if(config.Authentication.nodeAuthType === '' ||  undefined === config.Authentication.nodeAuthType) {
```

**Comment by NicolasDorier** [comment]
I needed to wipe out the RTL directory, this fixed it, but maybe there is another underlying cause?

**Comment by NicolasDorier** [comment]
Inside the directory, there is only RTL config file.... well I don't see how this could have been corrupted. The problem might have been my docker setup. Strange.

**Comment by NicolasDorier** [comment]
Closing this... to many unrelated strange file corruption in my system I must have messed up some unrelated thing.
