### ISSUE TITLE
RTL not syncing

### ISSUE THREAD

**Issue by fonzmeister** [ShahanaFarooqui/RTL#36]
**Describe the bug**
I have started the RTL node on my server running Ubuntu. It keeps on syncing forever and will not show any data. I am using autopilot btw, not sure if that behaviour is supported? My btc node and lnd node is working like expected. I have channels that are connected etc. It shows on https://1ml.com/node/0324957a5ab4f045fc02a492eb7a3ff375a4bcec059a6a31cdb6360a5aab7c53e0

**To Reproduce**
1. Go to 'cd /path/to/rtl'
2. 'node rt'

**Expected behavior**
It should be synced after a few minutes

**Actual behavior**
it keeps on loading

**Screenshots**

**Your environment**
* version of `lnd` 0.5.1
* operating system ubuntu server 18.04
* bitcoind

**Additional context**
lncli getinfo output
```

{
        "version": "0.5.1-beta commit=v0.5.1-beta-402-gcb1df51a3a2713c12cf55105ef64bbedae5d286e",
        "identity_pubkey": "0324957a5ab4f045fc02a492eb7a3ff375a4bcec059a6a31cdb6360a5aab7c53e0",
        "alias": "Cryptoleone",
        "num_pending_channels": 0,
        "num_active_channels": 18,
        "num_inactive_channels": 0,
        "num_peers": 21,
        "block_height": 558938,
        "block_hash": "0000000000000000000e2b30192cf1c2e84eb63230c9e8c6eece46827518d495",
        "best_header_timestamp": 1547755848,
        "synced_to_chain": true,
        "testnet": false,
        "chains": [
                {
                        "chain": "bitcoin",
                        "network": "mainnet"
                }
        ],
        "uris": [
                "0324957a5ab4f045fc02a492eb7a3ff375a4bcec059a6a31cdb6360a5aab7c53e0@145.53.159.48:9735"
        ]
}

```

output of the RTL node
```
Server is up and running, please open the UI at http://localhost:3000
Console:
Conf: 7: 1547756106097: INFO: Getting RTL Config
Console:
GetInfo: 9: 1547756106316: INFO: {"identity_pubkey":"0324957a5ab4f045fc02a492eb7a3ff375a4bcec059a6a31cdb6360a5aab7c53e0","alias":"Cryptoleone","num_active_channels":18,"num_peers":21,"block_height":558938,"block_hash":"0000000000000000000e2b30192cf1c2e84eb63230c9e8c6eece46827518d495","synced_to_chain":true,"uris":["0324957a5ab4f045fc02a492eb7a3ff375a4bcec059a6a31cdb6360a5aab7c53e0@145.53.159.48:9735"],"best_header_timestamp":"1547755848","version":"0.5.1-beta commit=v0.5.1-beta-402-gcb1df51a3a2713c12cf55105ef64bbedae5d286e","chains":[{"chain":"bitcoin","network":"mainnet"}]}

```

**Comment by saubyk** [comment]
hi @fonzmeister 

Can you please provide some more information on your setup.
Whats your RTL.conf like?
How are you trying to access RTL? Remotely or on the same machine on which RTL is running?

**Comment by fonzmeister** [comment]
I am trying to acces RTL on a different machine, on the same network though.
RTL runs on the same machine as my bitcoin and lnd node

Config:
```
[Authentication]
lndServerUrl=https://localhost:8080/v1
macroonPath=/home/USER/.lnd/data/chain/bitcoin/mainnet
nodeAuthType=CUSTOM
rtlPass=******
lndConfigPath=/home/USER/.lnd/lnd.conf
[Settings]
flgSidenavOpened=true
flgSidenavPinned=true
menu=Vertical
menuType=Regular
theme=dark-blue
satsToBTC=false

```

**Comment by saubyk** [comment]
This appears to be a strange issue.
It appears that your browser requests are reaching RTL, but rendering is a problem somehow.

I have a few more followup questions:
1. Which OS & Browser are you using for accessing RTL?
2. Did the npm install complete, without any errors?
3. Can you please post screenshots of the RTL page?
4. Can you please hit F12, click on the console and share the screen shot of the page, which appears to be loading?

Also, I would recommend taking a look at the below issue, try running npm install after installing the libraries for Ubuntu and test again.
https://github.com/ShahanaFarooqui/RTL/issues/27

Thanks.

**Comment by fonzmeister** [comment]
I deleted the folder and started from scratch.
Accessing the webpage from windows 10 & Chrome and the screenshot is attached
npm install gets a bunc of warnings and an error
```

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/@angular/compiler-cli/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN codelyzer@4.3.0 requires a peer of @angular/compiler@>=2.3.1 <7.0.0 || >6.0.0-beta <7.0.0 but none was installed.
npm WARN codelyzer@4.3.0 requires a peer of @angular/core@>=2.3.1 <7.0.0 || >6.0.0-beta <7.0.0 but none was installed.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.13 (node_modules/canvas):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.13 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```
```

gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/postema/.nvm/versions/node/v6.11.3/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 4.15.0-43-generic
gyp ERR! command "/home/postema/.nvm/versions/node/v6.11.3/bin/node" "/home/postema/.nvm/versions/node/v6.11.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/postema/RTL/node_modules/canvas
gyp ERR! node -v v6.11.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

```



![capture](https://user-images.githubusercontent.com/4063391/51429607-85b81900-1c10-11e9-87fb-108e4c66f48d.PNG)

**Comment by saubyk** [comment]
We may need to do live troubleshooting with you.
Please send me a DM on twitter @sauby_k, if you are ok with that. We can work out the media there.
Thanks.

**Comment by ITheSquid** [comment]
I had the same problem with the latest master build from lnd. They changed the output from "lncli getinfo". From
"chains": [
	"bitcoin"
	],
to
"chains": [
                {
                        "chain": "bitcoin",
                        "network": "mainnet"
                }
        ],
This is the related pull request: https://github.com/lightningnetwork/lnd/pull/2399
Zap-Desktop has the same problem. https://github.com/LN-Zap/zap-desktop/issues/1320#issuecomment-454014319
With an older lnd commit-version everything works without a problem.

**Comment by saubyk** [comment]
@fonzmeister please note the updated response above. Thanks.

**Comment by ShahanaFarooqui** [comment]
Closing this issue now. Hope RTL is working now on your setup. Feel free to open another, in case you face any issues. Thanks.

**Comment by fonzmeister** [comment]
Maybe I do not understand the above reactions, but it is not working.

I have lnd 0.5.1 beta as my lightning node. I have updated NPM and followed the instructions in the manual, but it still doesn't sync. WIll have time this evening and tomorrow to do it more thouroughly

**Comment by saubyk** [comment]
I re-opened the issue.
Can you please confirm, if you are running LND 0.5.1 from the master?

We are in the process of upgrading our test node from 0.5.0 to 0.5.1. Once we have the node synced, we will be able to provide a better update. Thanks.

**Comment by fonzmeister** [comment]
output of lncli getinfo

```
 lncli getinfo
{
        "version": "0.5.1-beta commit=v0.5.1-beta-402-gcb1df51a3a2713c12cf55105ef64bbedae5d286e",
        "identity_pubkey": "0324957a5ab4f045fc02a492eb7a3ff375a4bcec059a6a31cdb6360a5aab7c53e0",
        "alias": "Cryptoleone",
        "num_pending_channels": 1,
        "num_active_channels": 18,
        "num_inactive_channels": 0,
        "num_peers": 24,
        "block_height": 559613,
        "block_hash": "0000000000000000000f20addfff142b4b97b58e37bd11211d910b306f7fbb9e",
        "best_header_timestamp": 1548167136,
        "synced_to_chain": true,
        "testnet": false,
        "chains": [
                {
                        "chain": "bitcoin",
                        "network": "mainnet"
                }
        ],
        "uris": [
                "0324957a5ab4f045fc02a492eb7a3ff375a4bcec059a6a31cdb6360a5aab7c53e0@145.53.159.48:9735"
        ]
}

```

**Comment by ITheSquid** [comment]
Try to use the precompiled binaries of lnd found here https://github.com/lightningnetwork/lnd/releases

or based on your mentioned guide

```
cd $GOPATH/src/github.com/lightningnetwork/lnd
git checkout c1eaf6000030b672be5e4d6ecffcd3dd8057d3b9
make clean && make && make install
```
This will build lnd with one commit before the breaking change.
But i am not sure if your lnd version is backwards compatible with older versions of lnd.

If everything worked correctly your output of "lncli getinfo" should look like this 
```
...
        "synced_to_chain": true,
        "testnet": false,
        "chains": [
                "bitcoin"
        ],
...
```
and should not include this: ``` "network": "mainnet"``` 

This is just a temporary solution until RTL supports the new "lncli getinfo" output.

**Comment by fonzmeister** [comment]
I followed the steps above and RTL is working. lnd seems te be working as well. Will monitor for a while.

Thanks

**Comment by saubyk** [comment]
@ITheSquid thanks for the assist on this. We have added support for the new getinfo on our master.
Apparently a lot of people are actually running LND master branch, contrary to our expectation! Got pinged by some more folks. :-)

@fonzmeister feel free to test, or later when you want to upgrade to latest version of LND.

**Comment by fonzmeister** [comment]
Sorry for my late response. Just found enough time to update lnd and RTL and it is working. Thanks
