### ISSUE TITLE
Won't load wallet

### ISSUE THREAD

**Issue by ZapUser77** [ShahanaFarooqui/RTL#43]
**Describe the bug**
When I open localhost:3000 and log in... it asks me to "unlock my wallet" which is already unlocked.

**To Reproduce**
open localhost:3000 in a browser, login

**Expected behavior**
I expect it to work.

**Actual behavior**
It doesn't work.  It acts like it's trying to sync, and pops up a "unlock my wallet" password request.

**Screenshots**

**Your environment**
* version of `lnd`
0.5.1
* operating system (`uname -a` on *Nix)
 Rasbian
* version of `btcd`, `bitcoind`, or other backend 
BitcoinD
* any other relevant environment details

**Additional context**
[Authentication]
lndServerUrl=https://localhost:8080/v1
macroonPath=/home/pi/.lnd/data/chain/bitcoin/mainnet
nodeAuthType=CUSTOM
rtlPass=<Redacted>
lndConfigPath=/home/pi/.lnd/lnd.conf
enableLogging=false
[Settings]
flgSidenavOpened=true
flgSidenavPinned=true
menu=Vertical
menuType=Regular
theme=dark-blue
satsToBTC=false

Note: from within the app, I can view the lnd.conf and RTL.conf files.

**Comment by ZapUser77** [comment]
I just installed it, via "git clone https://github.com/ShahanaFarooqui/RTL.git" as per the instructions.

**Comment by saubyk** [comment]
do you have port 3000 open on the Raspberry pi?
You can check that by running `sudo ufw status`.

**Comment by ZapUser77** [comment]
No.  I'm running the web browser from the same device as LND/RTL.
Do I really need to open port 3000?

**Comment by ZapUser77** [comment]
That can't be it... if the firewall was the problem, the loading page wouldn't show up at all.

**Comment by ZapUser77** [comment]
The web interface sees RTL.conf and lnd.conf... but doesn't seem to see that LND is running, or something along those lines.

**Comment by saubyk** [comment]
Is your LND synced with Bitcoind?
Please run `lncli getinfo` on the command line and check.

**Comment by ZapUser77** [comment]
"synced_to_chain": true,"
Yes, it has been for about a year.  ^_^

**Comment by saubyk** [comment]
We would need to investigate the reason why LND api is failing.
Can you please do the below?
Run this command on the console...`sudo journalctl -f -u RTL`
Try logging into RTL from the browser.
The log should show the reason for the API failure. Paste the console output in the comment.

**Comment by saubyk** [comment]
Or you can update your RTL.conf with `enableLogging=true`
restart RTL
try logging in
RTL will generate a RTL.log file, which you share.

**Comment by saubyk** [comment]
You only shared a partial log above, its difficult to troubleshoot, if we cannot see the reason of LND API failure.
The reason why the application is taking you to "Unlock your wallet" screen, is because the getinfo API call failed from RTL. We need to understand the reason for the API failure to advise any further.

Also the `journalctl` command will only work, if you have configured RTL as a service on your pi.

**Comment by ZapUser77** [comment]
"may have been because your LND.conf does not have rpc password field"
I did explicitly state that it does.
"I couldn't long in via the bitcoind.rpcpass="
I guess I could have been more clear.  
There is a bitcoind.rpcpass= <Password redacted> with LND.conf that isn't being read properly.

git pull
npm install yields these errors:
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cairo' found
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/pi/.config/versions/node/v11.8.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Linux 4.14.30-v7+
gyp ERR! command "/home/pi/.config/versions/node/v11.8.0/bin/node" "/home/pi/.config/versions/node/v11.8.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/source/RTL/node_modules/canvas
gyp ERR! node -v v11.8.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

**Comment by ZapUser77** [comment]
Also, if there's a RTL.log file and you try to start node RTL... it errors you:
internal/modules/cjs/loader.js:613
    throw err;
    ^

Error: Cannot find module '/home/pi/source/RTL/RTL'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:611:15)
    at Function.Module._load (internal/modules/cjs/loader.js:537:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:801:12)
    at executeUserCode (internal/bootstrap/node.js:526:15)
    at startMainThreadExecution (internal/bootstrap/node.js:439:3)

**Comment by ZapUser77** [comment]
"Unlocking Wallet Failed! Verify That Lnd Is Running And The Wallet Is Locked!"

**Comment by ZapUser77** [comment]
I've checked the RTL.conf many times, everything is correct... 
But I have no idea what "lndServerUrl=https://localhost:8080/v1" is... which be the source of the problem, as I do not have anything running on HTTPS.

**Comment by saubyk** [comment]
lndServerUrl is the url on which LND is listening for the REST APIs, which RTL uses to interface with LND.
From the LND API documentation:
"The examples to the right assume that the there is a local lnd instance running and listening for REST connections on port 8080."

https://api.lightning.community/rest/index.html?javascript#lnd-rest-api-reference

**Comment by saubyk** [comment]
Still trying to figure out, what the problem might be with you setup.
At this point, it appears to be an environmental issue at your end. We are not able to reproduce the issue you are facing at our end. The way you are running RTL directly on rpi is also unique, as the device is too under-powered for this use case.
I can advise the following to fix the environmental issues before installing RTL.

1. Update your rpi
a. `sudo apt-get update`
b. `sudo apt-get dist-upgrade`
Cairo package dependency should be resolved with the above steps.

2. Test the LND REST API (with getinfo) on the rpi command line, with the following steps:
a. `MACAROON_HEADER="Grpc-Metadata-macaroon: $(xxd -ps -u -c 1000 /home/pi/.lnd/data/chain/bitcoin/mainnet/admin.macaroon)"`
b. `curl -X GET --cacert /home/pi/.lnd/tls.cert --header "$MACAROON_HEADER" https://localhost:8080/v1/getinfo`
It should return something like below:
{"identity_pubkey":"xxxxxxxxxxxxxxxcxxx12eab97facfxxxx1098385cxxxxx53d6bc40e52192xxxxxx","alias":"XXXXX","num_active_channels":12,"num_peers":15,"block_height":561719,"block_hash":"0000000000000000002caxxxxcx1b0xxx2e73ed8e1xxx61d8a0933b0xxxe3xxx","synced_to_chain":true,"chains":["bitcoin"],"uris":["xxxxxxxxxxxxxxxcxxx12eab97facfxxxx1098385cxxxxx53d6bc40e52192xxxxxx@xx.yyy.xxx.xx:1111"],"best_header_timestamp":"1549411611","version":"0.5.0-beta commit=3b2c80xxxxxb1b7xxxd609533c1e9xxx10ac5fxxx"}

3. run `npm install` in the RTL folder

npm install errors are environmental, and your installation needs to complete successfully for the application to run perfectly.

**Comment by ZapUser77** [comment]
"{"error":"all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: authentication handshake failed: x509: certificate is valid for 127.0.0.1, ::1, 192.168.1.100, 2405:9800:b910:8ee8:c93c:d208:f4b:4f3e, fe80::5e2f:9ca5:4308:93ec, not 0.0.0.0\"","code":14}"

this is what I get when I issue that curl.

**Comment by saubyk** [comment]
Please follow the below steps:
1. Stop LND
2. Delete your tls.key and tls.cert files from the lnd folder
3. Restart LND

Retry the curl command.

**Comment by ZapUser77** [comment]
Exact same error.

**Comment by saubyk** [comment]
Can you share your lnd.conf file?
You can mask the sensitive information like password or IP address etc.

**Comment by ZapUser77** [comment]
debuglevel=info
debughtlc=false
externalip=Removed
alias=Removed
color=Removed
maxpendingchannels=5
bitcoin.mainnet=1
bitcoin.active=1
bitcoin.node=bitcoind
bitcoind.rpcuser=Removed
bitcoind.rpcpass=Removed
restlisten=0.0.0.0:8080
bitcoind.zmqpubrawblock=tcp://127.0.0.1:18501
bitcoind.zmqpubrawtx=tcp://127.0.0.1:18502
rpclisten=0.0.0.0:10009
debughtlc=false

Ahh... maybe I need to delete that restlisten... I forgot I added that in there for testing.

**Comment by saubyk** [comment]
Try with this...

[Application Options]
debuglevel=info
debughtlc=false
externalip=Removed
alias=Removed
color=Removed
maxpendingchannels=5

[Bitcoin]
bitcoin.mainnet=1
bitcoin.active=1
bitcoin.node=bitcoind

[Bitcoind]
bitcoind.rpcuser=Removed
bitcoind.rpcpass=Removed
bitcoind.zmqpubrawblock=tcp://127.0.0.1:18501
bitcoind.zmqpubrawtx=tcp://127.0.0.1:18502

**Comment by saubyk** [comment]
On a separate note, RTL was not able to read the lnd.conf file correctly because the ini headers were missing in your file.
When you tried with authtype DEFAULT

**Comment by saubyk** [comment]
Please note, you need to restart and unlock LND, after you have updated the conf file.

**Comment by ZapUser77** [comment]
Worked like a champ.  Thanks for your assistance.
