### ISSUE TITLE
RTL errors if the macaroon is not found, can you instead wait or read the macaroon on demand?

### ISSUE THREAD

**Issue by NicolasDorier** [ShahanaFarooqui/RTL#72]
There is this error when starting RTL.
With BTCPay, LND only starts when the chain is fully synched, so we get log spam with RTL not being able to start.

Would it be possible to have one of those two workaround. (by order of preference)

1. Do not read macaroon preemptively, only when the user try to use RTL
2. Do not crash, but instead try again to read it at startup every 1 minutes.

```
Error: ENOENT: no such file or directory, open '/etc/lnd/admin.macaroon'
at Object.openSync (fs.js:439:3)
at Object.readFileSync (fs.js:344:35)
at setOptions (/RTL/connect.js:230:21)
at configFileExists (/RTL/connect.js:267:5)
at Object.<anonymous> (/RTL/connect.js:284:1)
at Module._compile (internal/modules/cjs/loader.js:689:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
at Module.load (internal/modules/cjs/loader.js:599:32)
at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
at Function.Module._load (internal/modules/cjs/loader.js:530:3)
at Module.require (internal/modules/cjs/loader.js:637:17)
at require (internal/modules/cjs/helpers.js:22:18)
at Object.<anonymous> (/RTL/controllers/getInfo.js:2:15)
at Module._compile (internal/modules/cjs/loader.js:689:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
at Module.load (internal/modules/cjs/loader.js:599:32)
at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
at Function.Module._load (internal/modules/cjs/loader.js:530:3)
at Module.require (internal/modules/cjs/loader.js:637:17)
at require (internal/modules/cjs/helpers.js:22:18)
at Object.<anonymous> (/RTL/routes/getInfo.js:1:86)
at Module._compile (internal/modules/cjs/loader.js:689:30)
fs.js:115
throw err;
```

**Comment by ShahanaFarooqui** [comment]
This has been addressed by following the first option per your suggestion.
Fixed with the release 0.2.14-beta.
